security:
    # Gestion du hash des mots de passe pour les utilisateurs
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers pour charger les utilisateurs en fonction de leur pseudo
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users       # Utilisation de l'entité Users
                property: pseudo              # Utilisation du pseudo pour l'authentification

    # Configuration des firewalls (pare-feu)
    firewalls:
        # Firewall pour le mode dev (exclut les assets et le profiler)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal pour la gestion de la sécurité des utilisateurs
        main:
            lazy: true
            provider: app_user_provider

            # Utilisation de votre UsersAuthenticator personnalisé
            custom_authenticator: App\Security\UsersAuthenticator

            # Configuration de la déconnexion
            logout:
                path: app_logout              # Route pour la déconnexion
                target: app_login             # Redirection après la déconnexion (vers la page de login)

            # Option pour se souvenir de l'utilisateur
            remember_me:
                secret: '%kernel.secret%'     # Clé secrète pour la fonction "se souvenir de moi"
                lifetime: 604800              # Durée de vie du cookie de 7 jours (en secondes)
                path: /

    # Contrôle d'accès pour définir les permissions selon les chemins
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
        - { path: ^/user, roles: ROLE_USER }

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_EMPLOYEE, ROLE_USER]
        ROLE_EMPLOYEE: [ROLE_USER]
