version: '3.8'

services:
  database:
    container_name: database_ecf
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: esportify
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network

  php:
    container_name: php_ecf
    build:
      context: .
      dockerfile: php/DockerFile
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
      - ./app:/var/www
    depends_on:
      - database
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ecf
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8899:80
    networks:
      - my_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_ecf
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Interface web
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
