# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #Un chemin qui me permet de avoir ou je met mes uploads sans avoir a réécrire le chemin a chaque fois
    uploads_directory: '%kernel.project_dir%/public/uploads/'
    redis_host: '127.0.0.1'
    redis_port: 6379

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Predis\Client:
        arguments:
            $parameters:
                host: '%redis_host%'
                port: '%redis_port%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

